### ISSUE TITLE
(Short name)

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-userstorys#1]
## Value statement - a requirement, not a solution
Als User
möchte ich nach Start der Anwendung eine Startseite sehen, auf der ich mein gewünschtes Torsystem auswählen kann.

### 

## Acceptance criteria
- [ ] Erstelle eine Page mit leerem Header und leerem Footer 
- [ ] Im Main-Bereich sind zwei große Grafik- oder Foto-Buttons für Sectionaltor und Rundlauftor

## Tasks
- [ ] Grafiken oder Fotos recherchieren

## Size
small

**Comment by s-kond** [comment]
Ich denke bei den Tasks müsstest du noch was ergänzen, nur durch die Fotorecherche entsteht ja noch keine Startseite... 🤔

**Comment by FrankOelsch** [comment]
Habe komplett überarbeitet.

**Comment by mpagels** [comment]
Good start here. But please write your user stories in English. It is the main communication language when it comes to programming.

Thinks I want to mention: Never put anything in your story that has no value to a user: A button that does nothing, has no value and confuses the user. An empty footer has no value. 

You could use this story on a later time, when the garage doors pages exist, and you can really navigate to it.

**Comment by FrankOelsch** [comment]
Changed again.
