### ISSUE TITLE
Konfigurations-Page

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-userstorys#2]
## Value statement - a requirement, not a solution
Als User
möchte ich nach Klick auf den Button "Sectionaltor" auf die Konfigurationsseite für Sectionaltore gelangen
um die Masse der Toröffnung einzugeben

## Acceptance criteria
- [ ] Nach Klick auf den oberen Button in der Startpage sieht der User die Konfigurations-Seite für (Decken-)Sectionaltore
- [ ] Im oberen Bereich ist eine Skizze der Toröffnung sichtbar, voreingestellt auf zB 200 x 200 cm mit Rundbogen zB 30 cm
- [ ] Darunter sind 3 Eingabefelder für Breite, Höhe und Radius mit vorgegebenen Werten sichtbar
- [ ] Alle Werte können geändert werden und bei 'Enter' oder Vertlassen des Eingabefeldes wird die Toröffnung animiert an die einegegebenen Werte angepasst

## Tasks
- [ ] Erstelle eine Page für die Konfiguration
- [ ] Erstelle oben einen canvas Bereich zur animierten Live-Darstellung der Toröffnung
- [ ] Erstelle darunter 3 Input-Felder type number
- [ ] Begrenze die Werte (min und max)
- [ ] Erstelle onChange Ereignisse
- [ ] Erstelle eine Funktion, die die eingegebenen Werte in eine Zeichnung auf dem canvas umwandelt
- [ ] Erstelle darunter einen Bereich für Meldungen
- [ ] Prüfe die Eingaben auf sinnvolle Werte und zeige Hinweis- bzw Fehlermeldungen an

## Size
medium

**Comment by s-kond** [comment]
Sieht gut aus finde ich 👍
