### ISSUE TITLE
Einbinden von Tests

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-userstorys#3]
## Value statement - a requirement, not a solution
Als Entwickler
will ich Tests schreiben
um die User-Eingaben automatisiert zu testen

## Acceptance criteria
- [ ] Bei einer Breite über 500 soll ein Hinweis erscheinen, dass Sectionaltore nur bis 500 cm Breite möglich sind
- [ ] Bei einer Breite unter 200 soll ein Hinweis erscheinen, dass Sectionaltore unterhalb 200 cm nicht angeboten werden
- [ ] Bei einer Breite über 450 und einer Höhe über 250 soll ein Hinweis erscheinen, dass das die Torfläche zu groß wird und diese Mass-Kombination nicht angeboten wird
- [ ] Bei einem Radius über 50% der Breite soll ein entsprechender Hinweis angezeigt werden

## Tasks
- [ ] Schreibe mindestens 3 Tests

## Size
medium
